apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tvzx-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-3uv4@sha256:0db89330fe6639ec0d85c7c95aa9fbc6bbff3f643f440725bf957b4d773ecf65
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
